export const ONBOARDING_STATUS_CONSTANTS = {
  EMAIL_VERIFICATION_PENDING: 'EMAIL_VERIFICATION_PENDING',
  USERNAME_PENDING: 'USERNAME_PENDING',
  ROLE_SELECTION_PENDING: 'ROLE_SELECTION_PENDING',
  PROFILE_COMPLETION_PENDING: 'PROFILE_COMPLETION_PENDING',
  ONBOARDING_STATUS_COMPLETED: 'ONBOARDING_STATUS_COMPLETED',
}

export const SIGN_UP_STEP_TYPE = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  SELECT_LANGUAGE: 'SELECT_LANGUAGE',
  CLAIM_URL: 'CLAIM_URL',
  CHOOSE_ROLE: 'CHOOSE_ROLE',
  BUILD_PROFILE: 'BUILD_PROFILE',
}

export const REGISTRATION_STATE_FLOW = [
  SIGN_UP_STEP_TYPE.CREATE_ACCOUNT,
  SIGN_UP_STEP_TYPE.VERIFY_EMAIL,
  SIGN_UP_STEP_TYPE.SELECT_LANGUAGE,
  SIGN_UP_STEP_TYPE.CLAIM_URL,
  SIGN_UP_STEP_TYPE.CHOOSE_ROLE,
  SIGN_UP_STEP_TYPE.BUILD_PROFILE,
]
